development:
  adapter: postgresql
  encoding: utf8
  database: development
  username: vitoroliveira
  password: 
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: test
  username: vitoroliveira
  password: 
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: production
  username: vitoroliveira
  password: